#!/bin/bash
#ports=$(egrep -A 22 "192.*" nmap2.txt  | grep open -B 4 | grep -v Host | grep -v "STATE" | grep -v "Not shown" | grep -v "MAC Address" | grep -v "Warning:" | egrep -v "\--" | grep -v "Nmap scan" | awk -F " " '{print $1,$3}' | sort | uniq
ports=("10000 snet-sensor-mgmt" "1025 NFS-or-IIS" "1026 LSA-or-nterm" "1027 IIS" "1030 iad1" "1031 iad2" "1036 nsstp"
"1037 ams" "1038 mtqp" "1042 afrog" "110 pop3" "111 rpcbind" "113 ident" "135 msrpc" "139 netbios-ssn"
"143 imap" "1521 oracle" "199 smux" "2030 device2" "2100 amiganetfs" "21 ftp" "22 ssh" "23 telnet"
"25 smtp" "3268 globalcatLDAP" "3269 globalcatLDAPssl" "32768 filenet-tms" "3306 mysql" "3372 msdtc" "3389 ms-wbt-server" "389 ldap" "443 https" "4443 pharos" "4445 upnotifyp" "445 microsoft-ds" "464 kpasswd5" "49152 unknown" "49153 unknown" "49154 unknown" "49155 unknown" "49156 unknown" "49157 unknown" "49158 unknown"
"49159 unknown" "49160 unknown" "5357 wsdapi" "53/tcp domain" "5800 vnc-http" "5900 vnc" "593 http-rpc-epmap"
"631 ipp" "636 ldapssl" "8000 http-alt" "8009 ajp13" "8080 http-proxy" "80 http" "88 kerberos-sec" "9090 zeus-admin" "993 imaps" "995 pop3s")



for port in "${ports[@]}" # for loop for each port in the listing
do 
   echo "$port" # formatting
   echo "===============================================================" #formating 
    num=$(echo $port | awk '{print $1}')    #grabbing just the port number
   grep -w "$num/tcp" -B 18 NMAP_all_hosts.txt | grep "192.*" | awk -F " " '{print $5}' #grabbing the ips for every instance of the port
  

   echo ""  #more formatting
        
  
done
