#!/bin/bash
count=0
while [ $count -lt 10000 ]
do

testMinute=$(systemctl is-active --quiet ssh && echo Service is running)
sleep 60

        if [ "$testMinute" == 'Service is running' ] 
        then
        echo $testMinute

        continue 

        else 
        echo $testMinute
        echo "starting SSH"
        systemctl start ssh
        fi

        count+=1


done 

#sudo systemctl stop ssh

